.TH .BINGURL 1 2021-11-03 "" ".bingUrl"
.SH NAME
.bingUrl \- .bingUrl(term, page)
.SH SYNOPSIS
\fI.bingUrl(term, page)\fR
.SH OPTIONS
.PP
\fBterm\fB \fR\- . 
.PP
.PP
\fBpage\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..bingUrl at search.R:line 30
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
