.TH GETCACHEPAGE 1 2021-11-03 "" "Get bing cached page"
.SH NAME
getCachePage \- getCachePage(link)
.SH SYNOPSIS
\fIgetCachePage(link)\fR
.SH DESCRIPTION
.PP
get cached page from bing server.
.PP
.SH OPTIONS
.PP
\fBlink\fB \fR\- . one result item from the bing search result list.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getCachePage at cache.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
