.TH SEARCH 1 2021-11-03 "" "Run bing search"
.SH NAME
search \- search(term, page = 1, .cache = ./.cache/)
.SH SYNOPSIS
\fIsearch(term, page = 1, .cache = ./.cache/)\fR
.SH OPTIONS
.PP
\fBterm\fB \fR\- . the search keyword
.PP
.PP
\fBpage\fB \fR\- 1. the page number of the bing search result.
.PP
.PP
\fB.cache\fB \fR\- ./.cache/. 
.PP
.SH VALUE
.PP
a list of search results in current search page, each result page link item in the result list may contains fields: + url: the result page url + title: the title of the target page
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.search at search.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
